"""create listing type table

Revision ID: 8462eab1e246
Revises: 3740c11828aa
Create Date: 2022-02-02 16:27:16.904760

"""
from operator import le

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision = '8462eab1e246'
down_revision = '3740c11828aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_types',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(length=50), nullable=False),
                    sa.Column('sub_type', sa.String(
                        length=50), nullable=False),
                    sa.Column('description', sa.String(
                        length=100), nullable=False),
                    sa.Column('meta', JSONB, default=lambda: {},
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing_types')
    # ### end Alembic commands ###
