"""create listing table

Revision ID: 9f8a44cb087e
Revises: 8462eab1e246
Create Date: 2022-02-02 16:32:55.229643

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision = '9f8a44cb087e'
down_revision = '8462eab1e246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('meta', JSONB, default=lambda: {},
                              nullable=False),
                    sa.Column('config_meta', JSONB, default=lambda: {},
                              nullable=False),
                    sa.Column('listing_type_id',
                              sa.BigInteger(), nullable=False),
                    sa.Column('listing_type', sa.String(
                        length=50), nullable=False),
                    sa.Column('listing_sub_type', sa.String(
                        length=50), nullable=False),
                    sa.Column('is_online', sa.Boolean(), nullable=False), # config_meta
                    sa.Column('is_paid', sa.Boolean(), nullable=False), # config_meta
                    sa.Column('is_featured', sa.Boolean(), nullable=False),# config_meta
                    sa.Column('is_published', sa.Boolean(), nullable=False),# config_meta
                    sa.Column('status', sa.Boolean(), nullable=False),
                    sa.Column('is_private', sa.Boolean(), nullable=False),#config_meta
                    sa.Column('has_disqus', sa.Boolean(), nullable=False), #config_meta
                    sa.Column('created_by_id',
                              sa.BigInteger(), nullable=False),
                    sa.Column('updated_by_id',
                              sa.BigInteger(), nullable=False),
                    sa.Column('publish_start_date', sa.TIMESTAMP, nullable=False,
                              server_default=sa.func.now(),
                              onupdate=sa.func.now()),
                    sa.Column('publish_end_date', sa.TIMESTAMP, nullable=False,
                              server_default=sa.func.now(),
                              onupdate=sa.func.now()),
                    sa.Column('created_at', sa.TIMESTAMP, nullable=False,
                              server_default=sa.func.now(),
                              onupdate=sa.func.now()),
                    sa.Column('updated_at', sa.TIMESTAMP, nullable=False,
                              server_default=sa.func.now(),
                              onupdate=sa.func.now()),
                    sa.PrimaryKeyConstraint('id'),
                    sa.ForeignKeyConstraint(
                        ['created_by_id'], ['users.id'], name=op.f('fk_created_by_id_users')),
                    sa.ForeignKeyConstraint(
                        ['updated_by_id'], ['users.id'], name=op.f('fk_updated_by_id_users')),
                    sa.ForeignKeyConstraint(
                        ['listing_type_id'], ['listing_types.id'], name=op.f('fk_listing_types_id_listing_types')),
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listings')
    # ### end Alembic commands ###
